[package]
name = "srex"
version = "0.1.0"
edition = "2021"

[lib]
name = "srex"

[dependencies]
hex = "0.4.3"

[dev-dependencies]
criterion = { version = "0.5.1", features = ["html_reports"] }

[[bench]]
name = "srecord"
harness = false
